version: '3.7'
services:
  php-fpm:
    build:
      context: php-fpm
    volumes:
      - ../:/var/www
    working_dir: /var/www
  nginx:
    build:
      context: nginx
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
  db:
    build:
      context: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=seenus
    ports:
      - "6080:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8765:80
    depends_on:
      - db
