#!/bin/bash

GIT_HOST=github.com
GIT_USER=btn441
GIT_REPOSITORY=docker-npmc
GIT_PATH=https://$GIT_HOST/$GIT_USER/$GIT_REPOSITORY.git

DOCKERS=Docker
PROJECTS=WebProjects

DIR_PATH=~/$DOCKERS/$GIT_REPOSITORY
DIR_DB=db_data
DIR_DB_PATH=$DIR_PATH/$DIR_DB
DIR_NGINX_SITES_PATH=$DIR_PATH/nginx/sites

# Главная
function main {
    menu
}

# Меню установочника
function menu {
    echo
    echo "Меню"
    echo "1 - Установить"
    echo "2 - Обновить"
    echo "3 - Удалить"
    echo -n "Что выбираешь? (1, 2 or 3) "

    read item

    case "$item" in
        1) 
            install
            ;;
        2) 
            update
            ;;
        3) 
            delete
            ;;
    esac
}

# Установка исполняемого файла, для Makefile
function create_docker_make {
    echo "make -f $DIR_PATH/Makefile ${1} ${2}" | sudo tee -a /bin/$GIT_REPOSITORY

    sudo chmod +x /bin/$GIT_REPOSITORY
}

# Установка репозитория
function install {
    function job {
        if [ -d "~/$DOCKERS" ]
        then
            mkdir ~/$DOCKERS
        fi

        if [ -d "~/$PROJECTS" ]
        then
            mkdir ~/$PROJECTS
        fi

        cd ~/$DOCKERS && git clone $GIT_PATH
        cd $GIT_REPOSITORY && docker-compose build
        sudo rm /bin/$GIT_REPOSITORY
        create_docker_make

        rm -rf $DIR_PATH/.git
        rm $DIR_PATH/.gitignore
        rm $DIR_PATH/$INSTALLER_NAME
    }

    if [ -d "$DIR_PATH" ]; then
        echo
        echo "Мы нашли директорию которую необходимо удалить!"
        echo "Вы хотите удалить $DIR_PATH? (Y|n)"

        read item

        case "$item" in
            y|Y)
                rm -rf $DIR_PATH
                job
                ;;
            n|N)
                exit 0
                ;;
            *) 
                rm -rf $DIR_PATH
                job
                ;;
        esac
    else
        job
    fi
}

# Обновление репозитория
function update {
    function job {
        sudo mv $DIR_DB_PATH /tmp/$GIT_REPOSITORY/$DIR_DB
        mv $DIR_NGINX_SITES_PATH /tmp/$GIT_REPOSITORY/sites
        rm -rf $DIR_PATH
        cd $DOCKERS && git clone $GIT_PATH
        cd $DIR_PATH && docker-compose build
        sudo rm -rf $DIR_DB_PATH
        rm -rf $DIR_NGINX_SITES_PATH
        sudo mv /tmp/$GIT_REPOSITORY/$DIR_DB $DIR_DB_PATH
        mv /tmp/$GIT_REPOSITORY/sites $DIR_NGINX_SITES_PATH
    }

    echo
    echo "Вы точно хотите обновить $GIT_REPOSITORY? (Y|n)"

    read item

    case "$item" in
        y|Y)
            job
            ;;
        n|N)
            exit 0
            ;;
        *) 
            job
            ;;
    esac    
}

# Удаление репозитория
function delete {
    function job {
        sudo rm /bin/$GIT_REPOSITORY
        rm -rf $DIR_PATH
    }
    
    echo
    echo "Вы точно хотите удалить $GIT_REPOSITORY? (Y|n)"

    read item

    case "$item" in
        y|Y)
            job
            ;;
        n|N)
            exit 0
            ;;
        *) 
            job
            ;;
    esac    
}

main
